"""empty message

Revision ID: 6921279d1dad
Revises: 0953ac85452b
Create Date: 2023-01-16 20:35:07.130254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6921279d1dad'
down_revision = '0953ac85452b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
